#!/usr/bin/env bash
# Cachage
# 2026-02-25 / 2026-03-23 18:52
# Hide bspwm windows on other workspaces for CPU usage optimisation
#
# Dependencies:
# - bspwm
#
# Usage:
# Keep running in the background. If you stop the script, run it with
# --restore after in order to unhide all the windows. If you restart
# the script, you need to unhide all the windows before starting it
# again or they will remain hidden.

NOM="${0##*/}"

kill_other_instances() {
    PIDS=$(pid=$BASHPID; pgrep -af "$0" | grep -v $pid | grep -v $$ | awk '{print $1}')
    if [ -z "$PIDS" ]; then
        [ "$1" = "interactive" ] && echo "$NOM: $T_NOTHINGTOKILL"
    else
        kill $PIDS
        printf "$NOM: ${T_KILLED}\n" "$PIDS"
    fi
}

restore() {
    bspc query -N -n .hidden | while read -r n; do
        bspc node "$n" -g hidden=off
    done
}

case "$1" in
    --restore|restore)
        restore
        exit
        ;;
    --list|list)
        ps aux | grep "$0" | grep -v "grep" | grep -v "$0 \(--\)\?list"
        exit
        ;;
    -r|--restart|r|restart)
        kill_other_instances
        restore
        ;;
    -k|--kill|k|kill)
        kill_other_instances interactive
        restore
        exit
        ;;
esac

declare -A focus
declare -a hidden
while read -r event _ desktop node; do
    case "$event" in
        desktop_focus)
            while read -r wid; do
                printf "%s\n" "${hidden[@]}" | grep -q "^${wid}$" &&
                    bspc node "$wid" -g hidden=off  # unhide if in hidden
                hidden=("${hidden[@]/$wid}")  # remove from hidden
            done < <(bspc query -N -n '.local.window.hidden')
            while read -r wid; do
                [ -n "$wid" ] && bspc node "$wid" -g hidden=on  # hide
                [ -n "$wid" ] && hidden+=("$wid")  # add to hidden
            done < <(bspc query -N -n '.!local.window.!hidden')
            [ -n "${focus[$desktop]}" ] && bspc node "${focus[$desktop]}" -f
            ;;
        node_focus)
            focus["$desktop"]="$node"
            ;;
    esac
done < <(bspc subscribe desktop_focus node_focus)
