#!/usr/bin/env python3
# chrom2csv
# 2026-07-06 19:19
"""Extracts selected information from Chromium bookmarks and history

Usage:
Bookmarks
    chrom2csv b ~/.config/chromium/Default/Bookmarks -st o.csv --sort a
History
    chrom2csv h ~/.config/chromium/Default/History -st o.csv --sort v

Known issues:
* Stale used dates if using --update and the containing folder hasn't
  changed. This is because only folders have modification dates and
  update uses them to decide which folders to enter, but these
  dates do not change when only use dates change, only if the
  name or url of a bookmark inside the folder changed.
"""
import os
import sys
import csv
import json
import sqlite3
import argparse
from datetime import datetime

PROG = 'chrom2csv'
DEFAULTSAVENAME = 'chrome.csv'
DATEFORMAT = '%F %T.%f'
QUIET = False

BOOKMARK_ROOTS = 'roots'
TOPLEVEL_BOOKMARK_FOLDERS = ["bookmark_bar", "other", "synced"]

BFORMATOPTIONS = {
    'A': 'added', 'a': 'added epoch', 'C': 'used', 'c': 'used epoch',
    'i': 'id', 'u': 'url', 'n': 'name', 'g': 'guid',
    'p': 'path', 'o': 'position',
}
DEFAULTBFORMATOPTIONS = 'iunaAcCpo'

HFORMATOPTIONS = {
    'V': 'visit', 'v': 'visit epoch',
    'i': 'id', 'u': 'url', 't': 'title',
    'r': 'from', 'n': 'transition', 'd': 'duration', 's': 'engagement score',
    'f': 'fk',
}
DEFAULTHFORMATOPTIONS = 'ifutvVds'
INTFIELDS = ['visit epoch', 'id', 'from', 'transition', 'duration',
             'engagement score', 'fk',]

S_UNDESIREDOVERWRITE = """
Exiting to avoid undesired overwriting.
Run with --overwrite if you wish to overwrite.
"""

# Args that we need in several commands but can't make top-level due
# to argument-order issues
REPEATEDARGS = [
    # Maybe there should be a different defaultsavename for each command
    (["-s", "--save"], {"action": "store_true", "help": f"""Save output to
file instead of printing to stdout. Will save to ./{DEFAULTSAVENAME} unless a
different path is provided with the -t/--save-to option."""}),
    (["-t", "--save-to"], {"help": """Path to save output to.
Ignored if -s/--save is not provided."""}),
    (["-o", "--overwrite"], {"action": "store_true", "help": """Overwrite
save file if it already exists. Ignored if -s/--save is not provided."""}),
    (["-u", "--update"], {"action": "store_true", "help": """Update save
file if it already exists. Ignored if -s/--save is not provided.
If both -o/--overwrite and -u/--update are provided,
overwrite will take precedence."""}),
]

COMMANDS = {
    "":                         # TOP LEVEL ARGS
    {"args": [
        (["--dryrun"], {"action": "store_true", "help": """
Don't write to disk."""}),
        (["-q", "--quiet"], {"action": "store_true", "help": """
Suppress messages in output."""}),
    ]},
    "b":                        # B (bookmarks)
    {"desc": "extract bookmarks data", "usage": """[-f FORMAT] [--sort SORT]
[-s] [-t SAVE_TO] [-o] [-u]
file""",
     "args": [
         (["file"], {"help": """Bookmarks file.
e.g. ~/.config/chromium/Default/Bookmarks"""}),
         (["-f", "--format"], {"default": DEFAULTBFORMATOPTIONS, "help": f"""
Which metadata fields to include and in which order. Default: {DEFAULTBFORMATOPTIONS}.
Options: {", ".join([f"{k} ({v})" for k, v in BFORMATOPTIONS.items()])}."""}),
         (["--sort"], {"choices":
                       [x for k in BFORMATOPTIONS for x in (k, k + 'r')],
                       "help": """Sort by a given metadata field.
Options are the same as for -f/--format, or followed by r for reverse order.
(Example: ir -> sort by id, reverse order.)"""}),
         *REPEATEDARGS,
     ]},
    "h":                        # H (history)
    {"desc": "extract history data", "usage": """[-f FORMAT] [--sort SORT]
[-s] [-t SAVE_TO] [-o] [-u]
file""",
     "args": [
         (["file"], {"help": """History file.
e.g. ~/.config/chromium/Default/History"""}),
         (["-f", "--format"], {"default": DEFAULTHFORMATOPTIONS, "help": f"""
Which metadata fields to include and in which order. Default: {DEFAULTHFORMATOPTIONS}.
Options: {", ".join([f"{k} ({v})" for k, v in HFORMATOPTIONS.items()])}."""}),
         (["--sort"], {"choices":
                       [x for k in HFORMATOPTIONS for x in (k, k + 'r')],
                       "help": """Sort by a given metadata field.
Options are the same as for -f/--format, or followed by r for reverse order.
(Example: ir -> sort by id, reverse order.)"""}),
         *REPEATEDARGS,
     ]},
}


def msg(text):
    # type: (str) -> None
    """Utility for logs/errors, could be replaced with proper logging"""
    if not QUIET:
        print(f'{PROG}: {text}')


def readable_date_from_epoch(e):
    """Takes epoch in microseconds since 1 January 1601 00:00 UTC"""
    # type: (int) -> str
    return datetime.fromtimestamp(e/1000000-11644473600).strftime(DATEFORMAT)


def epoch_from_readable_date(d):
    """Returns epoch in microseconds since 1 January 1601 00:00 UTC"""
    # type: (str) -> int
    return int(datetime.fromisoformat(d).timestamp()*1000000)+11644473600


def get_bookmark_information(d, fmt, path, position):
    res = {}

    a = d.get('date_added')
    c = d.get('date_last_used')

    dispatch = {
        'a': lambda: a,
        'A': lambda: readable_date_from_epoch(int(a)) if a and int(a) else '',
        'c': lambda: c,
        'C': lambda: readable_date_from_epoch(int(c)) if c and int(c) else '',
        'i': lambda: d.get('id'),
        'u': lambda: d.get('url'),
        'n': lambda: d.get('name'),
        'g': lambda: d.get('guid'),
        'p': lambda: path,
        'o': lambda: position,
    }

    for char in fmt:
        opt = BFORMATOPTIONS.get(char)
        if not opt or char not in dispatch:
            continue
        res[opt] = dispatch[char]()

    return res


def get_bookmarks_folder_generator(d, fmt, update_after=None, path=''):
    if d.get('type') == 'folder':
        if update_after and d.get('date_modified', 0) < update_after:
            return
        position = 0
        path = f'{path}/{d.get('name')}'
        for c in d.get('children', []):
            if c.get('type') == 'folder':
                yield from get_bookmarks_folder_generator(c, fmt, path)
            elif c.get('type') == 'url':
                yield get_bookmark_information(c, fmt, path, position)
                position += 1


def get_bookmarks_toplevel_generator(d, fmt, update_after=None):
    for g in [get_bookmarks_folder_generator(d.get(f, {}), fmt, update_after)
              for f in TOPLEVEL_BOOKMARK_FOLDERS]:
        yield from g


def get_bookmarks(d, fmt, update_after=None):
    return list(get_bookmarks_toplevel_generator(
        d[BOOKMARK_ROOTS], fmt, update_after))


def hquery(fmt):
    select = []

    q = {
        'v': f'v.visit_time "{HFORMATOPTIONS['v']}"',
        # formatted later in hformat
        'V': f'v.visit_time "{HFORMATOPTIONS['V']}"',
        'i': f'v.id "{HFORMATOPTIONS['i']}"',
        'u': f'u.url "{HFORMATOPTIONS['u']}"',
        't': f'u.title "{HFORMATOPTIONS['t']}"',
        'r': f'v.from_visit "{HFORMATOPTIONS['r']}"',
        'n': f'v.transition "{HFORMATOPTIONS['n']}"',
        'd': f'v.visit_duration "{HFORMATOPTIONS['d']}"',
        's': f'c.engagement_score "{HFORMATOPTIONS['s']}"',
        'f': f'v.url "{HFORMATOPTIONS['f']}"',
    }

    for char in fmt:
        opt = HFORMATOPTIONS.get(char)
        if not opt or char not in q:
            continue
        select.append(q[char])

    res = []
    if len(select):
        res.append(f'SELECT {', '.join(select)} from visits v')
        if 'u' in fmt or 't' in fmt:
            res.append('LEFT OUTER JOIN urls u ON v.url = u.id')
        if 's' in fmt:
            res.append(
                'LEFT OUTER JOIN clusters_and_visits c ON v.id = c.visit_id')

    return ' '.join(res)


def hformat(d):
    V = HFORMATOPTIONS['V']
    if d.get(V):
        d[V] = readable_date_from_epoch(d[V])
    return d


def parse_csv(s):
    # type: str -> list
    res = []
    rows = list(csv.DictReader(s.splitlines()))
    keys = list(rows[0].keys())
    for row in rows:
        r = {}
        for field in keys:
            r[field] = row[field]
        res.append(r)
    return res


def read_existing(path):
    # type: str -> dict
    existing = None
    with open(path, "r") as f:
        existing = parse_csv(f.read())
    return existing


def bhasfields(d, fmt, require_all=True):
    # type: (dict, str, bool) -> bool
    f = all if require_all else any
    return f(BFORMATOPTIONS.get(c) in d for c in fmt)


def bmerge(existing, new, fmt):
    # type: (list, list, str) -> list
    """Create dictionary from existing and new with only the fields in fmt
    and no duplicate IDs/GUIDs
    """
    if not existing:
        return new
    i = 'id' if bhasfields(existing[0], 'i') else 'guid'
    fields = [BFORMATOPTIONS[c] for c in fmt]
    by_id = {d[i]: {k: d[k] for k in fields} for d in existing}
    for d in new:
        by_id[d[i]] = d
    return list(by_id.values())


class CsvOutput():
    """Passed to csv module to get it write into a string instead of a file.
    Adapted from Bhavesh Poddar:
    https://levelup.gitconnected.com/building-csv-strings-in-python-32934aed5a9e
    """
    def __init__(self):
        self.lines = []

    def write(self, line):
        self.lines.append(line)

    def __str__(self):
        return ''.join(self.lines)


def export_csv(a):
    # type: (list) -> str
    fieldnames = [*list((a[0] if len(a) else {}).keys())]
    rows = [fieldnames]
    for item in a:
        rows.append([str(v) for v in item.values()])

    out = CsvOutput()
    writer = csv.writer(out)
    writer.writerows(rows)

    return str(out)


def cmd_b(args):
    save_to = args.save_to or DEFAULTSAVENAME

    existing = None
    update_after = None

    # Fail fast if save file already exists and overwrite is False
    # unless update is True
    if args.save and not args.overwrite:
        if os.path.exists(save_to):
            if not args.update:
                msg(f'Save file \'{save_to}\' already exists. '
                    'Run with -u/--update if you wish to update it. '
                    'Run with -o/--overwrite if you wish to overwrite it. '
                    'Run with -t/--save-to to specify a different save file.')
                exit(1)

            existing = read_existing(save_to)
            if not len(existing):
                msg('Existing is empty. Either the file is empty or something '
                    'went wrong.' + S_UNDESIREDOVERWRITE)
                exit(1)
            one = existing[0]
            # Check we have at least one of the date fields
            if not bhasfields(one, 'aAcC', require_all=False):
                msg('Existing data has no date fields. Without dates '
                    'in the data there is no reference point, so everything '
                    f'would have to be queried from scratch. {one}'
                    + S_UNDESIREDOVERWRITE)
                exit(1)
            # Check we have IDs or GUIDs
            if not bhasfields(one, 'ig', require_all=False):
                msg('Existing data has no IDs or GUIDs. Without identifiers '
                    'in the data there is no way to know which bookmarks were '
                    'modified.' + S_UNDESIREDOVERWRITE)
                exit(1)
            # Check format options are all there
            if not bhasfields(one, args.format, require_all=True):
                msg('Existing data does not contain all format '
                    'options, so everything would have to be queried from '
                    f'scratch. {one} | {args.format}'
                    + S_UNDESIREDOVERWRITE)
                exit(1)
            else:               # Proceed with the update
                # Sort data in order to get the most recent date in it
                a = c = 0
                if bhasfields(one, 'a', require_all=False):
                    existing.sort(key=lambda r: r[BFORMATOPTIONS['a']])
                    a = existing[-1].get(BFORMATOPTIONS['a'])
                elif bhasfields(one, 'A', require_all=False):
                    existing.sort(key=lambda r: r[BFORMATOPTIONS['A']])
                    A = existing[-1].get(BFORMATOPTIONS['A'])
                    a = epoch_from_readable_date(A)
                if bhasfields(one, 'c', require_all=False):
                    existing.sort(key=lambda r: r[BFORMATOPTIONS['c']])
                    c = existing[-1].get(BFORMATOPTIONS['c'])
                elif bhasfields(one, 'C', require_all=False):
                    existing.sort(key=lambda r: r[BFORMATOPTIONS['C']])
                    C = existing[-1].get(BFORMATOPTIONS['C'])
                    c = epoch_from_readable_date(C)
                update_after = a if a > c else c
                msg('Updating bookmarks after '
                    f'{update_after} '
                    f'({readable_date_from_epoch(int(update_after))})')

    with open(args.file, 'r') as f:
        data = json.load(f)

    bookmarks = get_bookmarks(data, args.format, update_after)

    if update_after and not bookmarks:
        msg("No new data")

    bookmarks = bmerge(
        existing, bookmarks, args.format) if update_after else bookmarks

    def sort_key(item):
        k = BFORMATOPTIONS[args.sort[0]]
        data_to_sort_by = item.get(k, None)
        if data_to_sort_by is None:
            msg(f"{k} not in entry data")
            data_to_sort_by = ''
        return data_to_sort_by

    if args.sort:
        reverse = True if len(args.sort) > 1 and args.sort[1] == 'r' else False
        msg(f'Sorting by {args.sort[0]}{" in reverse" if reverse else ""}')
        bookmarks.sort(key=sort_key, reverse=reverse)

    dump = export_csv(bookmarks)

    if args.save and not args.dryrun:
        open_as = 'w' if args.overwrite or args.update else 'x'
        with open(save_to, open_as) as f:
            f.write(dump)
            msg(f'Wrote to {save_to}')
    else:
        print(dump)


def parse_args():
    parser = argparse.ArgumentParser(prog=PROG)
    parser.suggest_on_error = True
    subparsers = parser.add_subparsers(dest="command", required=True)
    descs = []
    for k, v in COMMANDS.items():
        if v.get('desc'):       # description generation
            descs.append(f"{v['desc']} ({k})")
        if k == "":             # arguments on top parser
            for args, kwargs in v['args']:
                parser.add_argument(*args, **kwargs)
            continue
        subparser = subparsers.add_parser(
            k, help=f"[-h|--help] {v.get('usage')}")
        for args, kwargs in v['args']:
            subparser.add_argument(*args, **kwargs)
        # Set handler
        subparser.set_defaults(func=v.get('func'))
    # Add generated description
    if len(descs) > 1:
        descs[-1] = f"or {descs[-1]}"
    parser.description = f"A utility script to \
{' '.join(descs)} from Chromium files."
    # Parse args / print help and quit if no args
    # (Primer https://stackoverflow.com/a/47440202/18396947)
    return parser.parse_args(sys.argv[1:] or ['--help'])


def cmd_h(args):
    if args.update:
        raise NotImplementedError()

    # Fail fast if save file already exists and overwrite is False
    # unless update is True
    if args.save and not args.overwrite:
        if os.path.exists(args.save_to):
            if not args.update:
                msg(f'Save file \'{args.save_to}\' already exists. '
                    'Run with -u/--update if you wish to update it. '
                    'Run with -o/--overwrite if you wish to overwrite it. '
                    'Run with -t/--save-to to specify a different save file.')
                exit(1)

    with sqlite3.connect(
            f"file:{args.file}?mode=ro&nolock=1", uri=True) as con:
        con.row_factory = sqlite3.Row
        con.text_factory = lambda data: str(data, errors="surrogateescape")
        cur = con.cursor()
        res = cur.execute(hquery(args.format))

    visits = [hformat(dict(s)) for s in res]

    def sort_key(item):
        k = HFORMATOPTIONS[args.sort[0]]
        data_to_sort_by = item.get(k, None)
        if data_to_sort_by is None:
            msg(f"{k} not in entry data")
            data_to_sort_by = 0 if k in INTFIELDS else ''
        return data_to_sort_by

    if args.sort:
        reverse = True if len(args.sort) > 1 and args.sort[1] == 'r' else False
        msg(f'Sorting by {args.sort[0]}{" in reverse" if reverse else ""}')
        visits.sort(key=sort_key, reverse=reverse)

    dump = export_csv(visits)

    if args.save and not args.dryrun:
        open_as = 'w' if args.overwrite or args.update else 'x'
        with open(args.save_to, open_as) as f:
            f.write(dump)
            msg(f'Wrote to {args.save_to}')
    else:
        print(dump)


COMMANDS['b']['func'] = cmd_b
COMMANDS['h']['func'] = cmd_h


def main():
    # type: () -> None
    global QUIET

    args = parse_args()
    QUIET = args.quiet

    args.func(args)


if __name__ == '__main__':
    main()
