#!/usr/bin/env python3
# chrom2csv
# 2026-07-06 19:19
"""Extracts selected information from Chromium bookmarks

Usage:
    chrom2csv b ~/.config/chromium/Default/Bookmarks
"""
import os
import sys
import csv
import json
import argparse
from datetime import datetime

PROG = 'chrom2csv'
DEFAULTSAVENAME = 'bookmarks.csv'
DATEFORMAT = '%F %T.%f'
QUIET = False

BOOKMARK_ROOTS = 'roots'
TOPLEVEL_BOOKMARK_FOLDERS = ["bookmark_bar", "other", "synced"]

BFORMATOPTIONS = {
    'A': 'added', 'a': 'added epoch', 'C': 'used', 'c': 'used epoch',
    'i': 'id', 'u': 'url', 'n': 'name', 'g': 'guid',
}
DEFAULTBFORMATOPTIONS = 'iunaAcC'

COMMANDS = {
    "":                         # TOP LEVEL ARGS
    {"args": [
        (["--dryrun"], {"action": "store_true", "help": """
Don't write to disk."""}),
        (["-q", "--quiet"], {"action": "store_true", "help": """
Suppress messages in output."""}),
    ]},
    "b":                        # B (bookmarks)
    {"desc": "extract bookmarks data", "usage": """[-f FORMAT] [--sort SORT]
[-s] [-t SAVE_TO] [-o] [-u]
file""",
     "args": [
         (["file"], {"help": """Bookmarks file.
e.g. ~/.config/chromium/Default/Bookmarks"""}),
         (["-f", "--format"], {"default": DEFAULTBFORMATOPTIONS, "help": f"""
Which metadata fields to include and in which order. Default: {DEFAULTBFORMATOPTIONS}.
Options: {", ".join([f"{k} ({v})" for k, v in BFORMATOPTIONS.items()])}."""}),
         (["--sort"], {"choices":
                       [x for k in BFORMATOPTIONS for x in (k, k + 'r')],
                       "help": """Sort by a given metadata field.
Options are the same as for -f/--format, or followed by r for reverse order.
(Example: ir -> sort by id, reverse order.)"""}),
         (["-s", "--save"], {"action": "store_true", "help": f"""Save output to
file instead of printing to stdout. Will save to ./{DEFAULTSAVENAME} unless a
different path is provided with the -t/--save-to option."""}),
         (["-t", "--save-to"], {"help": """Path to save output to.
Ignored if -s/--save is not provided."""}),
         (["-o", "--overwrite"], {"action": "store_true", "help": """Overwrite
save file if it already exists. Ignored if -s/--save is not provided."""}),
         (["-u", "--update"], {"action": "store_true", "help": """Update save
file if it already exists. Ignored if -s/--save is not provided.
If both -o/--overwrite and -u/--update are provided,
overwrite will take precedence."""}),
     ]},
}


def msg(text):
    # type: (str) -> None
    """Utility for logs/errors, could be replaced with proper logging"""
    if not QUIET:
        print(f'{PROG}: {text}')


def readable_date_from_epoch(e):
    """Takes epoch in microseconds since 1 January 1601 00:00 UTC"""
    # type: (int) -> str
    return datetime.fromtimestamp(e/1000000-11644473600).strftime(DATEFORMAT)


def get_bookmark_information(d, fmt):
    res = {}

    a = int(d.get('date_added'))
    c = int(d.get('date_last_used'))

    dispatch = {
        'a': lambda: a,
        'A': lambda: readable_date_from_epoch(a) if a else None,
        'c': lambda: c,
        'C': lambda: readable_date_from_epoch(c) if c else None,
        'i': lambda: d.get('id'),
        'u': lambda: d.get('url'),
        'n': lambda: d.get('name'),
        'g': lambda: d.get('guid'),
    }

    for char in fmt:
        opt = BFORMATOPTIONS.get(char)
        if not opt or char not in dispatch:
            continue
        res[opt] = dispatch[char]()

    return res


def get_bookmarks_folder_generator(d, fmt):
    t = d.get('type')
    if t == 'folder':
        for c in d.get('children', []):
            yield from get_bookmarks_folder_generator(c, fmt)
    elif t == 'url':
        yield get_bookmark_information(d, fmt)


def get_bookmarks_toplevel_generator(d, fmt):
    for g in [get_bookmarks_folder_generator(d.get(f, {}), fmt)
              for f in TOPLEVEL_BOOKMARK_FOLDERS]:
        yield from g


def get_bookmarks(d, fmt):
    return list(get_bookmarks_toplevel_generator(d[BOOKMARK_ROOTS], fmt))


class CsvOutput():
    """Passed to csv module to get it write into a string instead of a file.
    Adapted from Bhavesh Poddar:
    https://levelup.gitconnected.com/building-csv-strings-in-python-32934aed5a9e
    """
    def __init__(self):
        self.lines = []

    def write(self, line):
        self.lines.append(line)

    def __str__(self):
        return ''.join(self.lines)


def export_csv(a):
    # type: (list) -> str
    fieldnames = [*list((a[0] if len(a) else {}).keys())]
    rows = [fieldnames]
    for item in a:
        rows.append([str(v) for v in item.values()])

    out = CsvOutput()
    writer = csv.writer(out)
    writer.writerows(rows)

    return str(out)


def cmd_b(args):
    save_to = args.save_to or DEFAULTSAVENAME

    if args.update:
        raise NotImplementedError()

    # Fail fast if save file already exists and overwrite is False
    # unless update is True
    if args.save and not args.overwrite:
        if os.path.exists(save_to):
            if not args.update:
                msg(f'Save file \'{save_to}\' already exists. '
                    'Run with -u/--update if you wish to update it. '
                    'Run with -o/--overwrite if you wish to overwrite it. '
                    'Run with -t/--save-to to specify a different save file.')
                exit(1)

    with open(args.file, 'r') as f:
        data = json.load(f)

    bookmarks = get_bookmarks(data, args.format)

    def sort_key(item):
        k = BFORMATOPTIONS[args.sort[0]]
        data_to_sort_by = item.get(k, None)
        if data_to_sort_by is None:
            msg(f"{k} not in entry data")
            data_to_sort_by = ''
        return data_to_sort_by

    if args.sort:
        reverse = True if len(args.sort) > 1 and args.sort[1] == 'r' else False
        msg(f'Sorting by {args.sort[0]}{" in reverse" if reverse else ""}')
        bookmarks.sort(key=sort_key, reverse=reverse)

    dump = export_csv(bookmarks)

    if args.save and not args.dryrun:
        open_as = 'w' if args.overwrite or args.update else 'x'
        with open(save_to, open_as) as f:
            f.write(dump)
            msg(f'Wrote to {save_to}')
    else:
        print(dump)


def parse_args():
    parser = argparse.ArgumentParser(prog=PROG)
    parser.suggest_on_error = True
    subparsers = parser.add_subparsers(dest="command", required=True)
    descs = []
    for k, v in COMMANDS.items():
        if v.get('desc'):       # description generation
            descs.append(f"{v['desc']} ({k})")
        if k == "":             # arguments on top parser
            for args, kwargs in v['args']:
                parser.add_argument(*args, **kwargs)
            continue
        subparser = subparsers.add_parser(
            k, help=f"[-h|--help] {v.get('usage')}")
        for args, kwargs in v['args']:
            subparser.add_argument(*args, **kwargs)
        # Set handler
        subparser.set_defaults(func=v.get('func'))
    # Add generated description
    if len(descs) > 1:
        descs[-1] = f"or {descs[-1]}"
    parser.description = f"A utility script to \
{' '.join(descs)} from Chromium files."
    # Parse args / print help and quit if no args
    # (Primer https://stackoverflow.com/a/47440202/18396947)
    return parser.parse_args(sys.argv[1:] or ['--help'])


COMMANDS['b']['func'] = cmd_b


def main():
    # type: () -> None
    global QUIET

    args = parse_args()
    QUIET = args.quiet

    args.func(args)


if __name__ == '__main__':
    main()
