#!/usr/bin/env bash

dunstctl close-all
json=$(dunstctl history)

# Uptime système en secondes (horloge boottime)
uptime_s=$(cut -d' ' -f1 /proc/uptime)

choice=$(echo "$json" | jq -r --compact-output --argjson uptime "$uptime_s" '
[
  .data[0][] |
  .id.data as $id |

  (.summary.data | gsub("\n"; " > ")) as $summary_clean |
  ($summary_clean |
   if length > 74 then .[0:77] + "..." else . end) as $preview |
($preview | if length > 35 then .[0:35] + "\n" + .[35:] else . end) as $preview |

  (.timestamp.data / 1000000 | floor) as $timestamp_s |
  ($uptime - $timestamp_s) as $age_s |

  # format humain
  (if $age_s < 60 then "\($age_s|floor)s"
   elif $age_s < 3600 then "\(($age_s/60)|floor)m"
   elif $age_s < 86400 then "\(($age_s/3600)|floor)h"
   else "\(($age_s/86400)|floor)d"
   end) as $age |

  "<b>\($id)) <span foreground=\"#cc7799\">\($age)</span></b> \"\($preview)\""
] | join("\u001e")
' | head -c -1 | rofi -sep '\x1e' -eh 2 -i -no-cycle -markup-rows -dmenu -kb-accept-alt "" -kb-custom-1 "Shift+Return" -p "cp notification")
ret=$?

# Rien faire si aucune notif
# [ -z "$list" ] && exit 0
#echo -en "$list"
# Ouvrir rofi
# choice=$(echo -en "$list" | rofi -sep '\x1e' -eh 2 -i -no-cycle -markup-rows -dmenu -p "cp notification")

# Rien faire si rien choisi
[ -z "$choice" ] && exit 0

# Extraire l'ID sélectionné
# modifie le -d')' su tu changes le format dans jq
id=$(echo "$choice" | head -1 | cut -d')' -f1 | cut -d'>' -f2 | tr -d ' ')

# Récupérer le summary correspondant
summary=$(echo "$json" | jq -r --arg id "$id" '
  .data[0][] | select(.id.data == ($id|tonumber)) | .summary.data
')

if [ $ret == 10 ]; then
    if command -v pipe-to-emacs >/dev/null 2>&1; then
        echo -n "$summary" | pipe-to-emacs fundamental-mode
    fi
else
    echo -n "$summary" | xclip -selection clipboard
fi

# ----- NOTES

# pour extraire juste la première ligne si besoin :
# (.summary.data | split("\n")[0]) as $first

# conversion en date
# #   # timestamp formaté (µs → s → date)
# #   (.timestamp.data / 1000000 | todate) as $date |

# debogage du timestamp
#  #"\($id) | \($timestamp_s) \($uptime) | \($preview)"

# caractère mignon mais malheureusement casse la hauteur des lignes
# ⏎

# avec icône
#  "<b>\($id)) <span foreground=\"#cc7799\">\($age)</span></b> \"\($preview)\"\u0000icon\u001forg.xfce.about"
