#!/usr/bin/env sh
# Emacs sudo editor in terminal
# 2025-12-07 18:34
#
# Dependencies:
# - Emacs server (M-x server-start)
#
# Usage:
# em
# em "file to edit"
# em /etc/fstab

if [ -z "$1" ]; then
    emacsclient -t
else
    case "$1" in
        /*) emacsclient -t /sudo::"$1";;
        *) emacsclient -t /sudo::"${PWD}/$1";;
    esac
fi
