#!/usr/bin/env sh
# Save and open favourite images in feh
# 2026-01-01 14:03
#
# Dependencies:
# - rofi
# - (Optional) script pfeh to launch feh with custom options
#
# Usage:
# feh actions
# --action1 'fehfavoris'
# --action2 'fehfavoris "%f"'
# 1 opens favourites, 2 saves current image to favourites
# Saves the list of favourites in ~/.fehfavoris
# Shift+Enter to remove an image from the list

FAVORISFICHIER="$HOME/.fehfavoris"
ROFITITLE="favoris"
REMHOTKEY="Shift+Return"
T_EMPTY="Pas de favoris."
T_DOESNTEXIST="Erreur : le chemin n'existe pas."
T_DUPLICATE="Déjà dans les favoris."
T_SUCCESS="Ajouté aux favoris."

NOM="${0##*/}"

if [ ! -f "$FAVORISFICHIER" ]; then
    touch "$FAVORISFICHIER"
fi

if [ -z "$1" ]; then
    options=$(cat "$FAVORISFICHIER")
    if [ -z "$options" ]; then
        echo "$NOM: $T_EMPTY"
        exit
    fi
    res=$(echo -en "$options" | rofi -i -no-cycle -dmenu -kb-accept-alt "" -kb-custom-1 "$REMHOTKEY" -p "$ROFITITLE")
    ret=$?
    if [ -e "$res" ]; then
        if [ $ret == 10 ]; then
            # remove from list of favourites
            sed -i "\|$res|d" "$FAVORISFICHIER"
        else
            command -v pfeh >/dev/null 2>&1 &&
                pfeh --start-at "$res" ||
                    feh --start-at "$res"
        fi
    fi
    exit
fi

CHEMIN=$(realpath "$1" 2>/dev/null)
if [ ! -e "$CHEMIN" ]; then
    echo "$NOM: $T_DOESNTEXIST"
    exit 1
fi

if grep -Fxq "$CHEMIN" "$FAVORISFICHIER"; then
    echo "$NOM: $T_DUPLICATE"
else
    # add to list of favourites
    echo "$CHEMIN" >> "$FAVORISFICHIER"
    echo "$NOM: $T_SUCCESS"
fi
