#!/usr/bin/env sh
# interlacevids - download and interlace two or more videos
# 2026-08-12 04:54
#
# Dependencies:
# - yt-dlp
# - ffmpeg
#
# Usage:
# mkdir dirforvideofiles
# interlacevids youtube.com/watch?v=xyLRG5P-HSU youtube.com/watch?v=w4OHnWwS5d0

NOM="${0##*/}"
YTDLPARGS="-f worst"
SUBDIR="segments"
T=30  # Size of each segment in seconds

help() {
    cat <<EOF
Usage: $NOM [options] link1 link2 ...

Options:

-h | --help   Show this help text and exit.
--nodownload  Don't download the video links (will use existing "$NOM-vid\$i"
              files).

Examples:
* $NOM youtube.com/watch?v=xyLRG5P-HSU youtube.com/watch?v=w4OHnWwS5d0
EOF
}

nodownload_flag=0

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            help
            exit;;
        --nodownload)
            nodownload_flag=1;;
        --)
            shift
            break;;
        -*)
            echo "$NAME: Unknown option $1" >&2
            exit 1;;
        *)
            break;;
    esac
    shift
done

if [ -z "$1" ] || [ -z "$2" ]; then
    printf "$NOM: requires 2 or more video links\n"
    exit 1
fi

i=1

if [ "$nodownload_flag" = 0 ]; then
    for lien in "$@"; do
        V="$NOM-vid$i"

        if ! yt-dlp $YTDLPARGS -o "$V" "$lien"; then
            printf '%s: fatal: video %d download failed\n' "$NOM" "$i" >&2
            exit 1
        fi

        i=$((i + 1))
    done
fi

if ! mkdir "$SUBDIR"; then
    printf "$NOM: fatal: can't create $SUBDIR subdir\n"
    exit 1
fi

cd "$SUBDIR"

i=1

for lien in "$@"; do
    V="$NOM-vid$i"

    if ! ffmpeg -i ../"$V" -map 0 -c copy -f segment -segment_time "$T" -reset_timestamps 1 vid$i-%03d.mp4; then
        printf '%s: fatal: cutting video %d into segments failed\n' "$NOM" "$i" >&2
        exit 1
    fi

    i=$((i + 1))
done

i=$((i - 1))

python3 <<PY
from pathlib import Path

vids = {}

for i in range(1, ${i} + 1):
    vids[i] = sorted(Path(".").glob(f"vid{i}-*"))

segments = []

for i in range(max(len(v) for v in vids.values())):
    for k, v in vids.items():
        if i < len(v):
            segments.append((v[i], f"vid{k} segment {i + 1}"))

with open("concat.txt", "w", encoding="utf-8") as f:
    for path, _ in segments:
        f.write(f"file '{path}'\n")

with open("chapters.txt", "w", encoding="utf-8") as f:
    f.write(";FFMETADATA1\n\n")

    for i, (_, title) in enumerate(segments):
        start = i * ${T}_000
        end = (i + 1) * ${T}_000

        f.write("[CHAPTER]\n")
        f.write("TIMEBASE=1/1000\n")
        f.write(f"START={start}\n")
        f.write(f"END={end}\n")
        f.write(f"title={title}\n\n")
PY

cd ..
ffmpeg -f concat -safe 0 -i "$SUBDIR/concat.txt" -i "$SUBDIR/chapters.txt" -map 0 -map_metadata 1 -c copy interlaced.mp4
