#!/usr/bin/env bash

sonpause="/home/pm/Downloads/pronunciation_fr_une_pause_pipi.mp3"
sonunpause="/home/pm/Downloads/pronunciation_fr_alors,_on_continue__.mp3"
NOM="${0##*/}"

has_paplay=$(command -v paplay >/dev/null 2>&1 && echo true)
has_emacs=$(command -v emacsclient >/dev/null 2>&1 && echo true)

kill_other_instances() {
    PIDS=$(ps aux | grep "$0" | grep -v grep | grep -v k | grep -v kill | awk '{print $2}')
    if [ -z "$PIDS" ]; then
        [ "$1" = "interactive" ] && echo "$NOM: aucun processus à tuer."
    else
        kill $PIDS
        echo "$NOM: processus tués : $PIDS"
    fi
}

case "$1" in
    list)
        ps aux | grep "$0" | grep -v "grep" | grep -v "$0 list"
        exit
        ;;
    r|restart)
        kill_other_instances
        ;;
    k|kill)
        kill_other_instances interactive
        exit
        ;;
esac

joue() {
    [ $has_paplay = true ] && paplay "$1"
}

message() {
    msg="$NOM: $1"
    echo "$msg"
    [ $has_emacs = true ] && emacsclient --eval "(message \"$msg\")" >/dev/null 2>&1
}

do_pause() {
    joue "$sonpause"
    message pause
}

do_continue() {
    joue "$sonunpause"
    message continue
}

# main loop
(
    while true; do
        sleep 25m
        do_pause
        sleep 5m
        do_continue
    done
) & disown
