#!/usr/bin/env python3
# places2csv
# 2026-06-29 03:37
"""Extracts selected information from places.sqlite

Usage:
    places2csv ~/.mozilla/firefox/*.default-release/places.sqlite -st ~/out.csv --sort v  # noqa: E501

(the noqa is just to avoid flake8 shouting at me for line length, you
don't need it in the command, but it won't hurt either since # is a
comment in most shells)

Note that the same id can appear multiple times (it generates a row
per visit, the id is the place id, and the same place can have
multiple visits)
"""
import os
import sys
import csv
import sqlite3
import argparse
from datetime import datetime

PROG = 'places2csv'
DEFAULTSAVENAME = 'places.csv'
# Caution: If the date format is changed to less precision, there will
# be an issue with duplicates when updating data with no epoch field
DATEFORMAT = '%F %T.%f'
QUIET = False

HFORMATOPTIONS = {
    'V': 'visit', 'v': 'visit epoch',
    'i': 'id', 'u': 'url', 't': 'title', 'd': 'description',
}
DEFAULTHFORMATOPTIONS = 'iutvV'

BFORMATOPTIONS = {
    'A': 'added', 'a': 'added epoch',
    'M': 'modified', 'm': 'modified epoch',
    'i': 'id', 'u': 'url', 't': 'title', 'p': 'path', 'k': 'keyword',
    'f': 'fk',
}
DEFAULTBFORMATOPTIONS = 'iutaAmMpk'

INTFIELDS = (HFORMATOPTIONS['v'], HFORMATOPTIONS['i'],
             BFORMATOPTIONS['m'], BFORMATOPTIONS['a'])

S_UNDESIREDOVERWRITE = """
Exiting to avoid undesired overwriting.
Run with --overwrite if you wish to overwrite.
"""

# Args that we need in several commands but can't make top-level due
# to argument-order issues
REPEATEDARGS = [
    (["places_sqlite"], {"help": """places.sqlite file."""}),
    # Maybe there should be a different defaultsavename for each command
    (["-s", "--save"], {"action": "store_true", "help": f"""Save output to
file instead of printing to stdout. Will save to ./{DEFAULTSAVENAME} unless a
different path is provided with the -t/--save-to option."""}),
    (["-t", "--save-to"], {"help": """Path to save output to.
Ignored if -s/--save is not provided."""}),
    (["-o", "--overwrite"], {"action": "store_true", "help": """Overwrite
save file if it already exists. Ignored if -s/--save is not provided."""}),
    (["-u", "--update"], {"action": "store_true", "help": """Update save
file if it already exists. Ignored if -s/--save is not provided.
If both -o/--overwrite and -u/--update are provided,
overwrite will take precedence."""}),
]

COMMANDS = {
    "":                         # TOP LEVEL ARGS
    {"args": [
        (["--dryrun"], {"action": "store_true", "help": """
Don't write to disk."""}),
        (["-q", "--quiet"], {"action": "store_true", "help": """
Suppress messages in output."""}),
    ]},
    "h":                        # H (history)
    {"desc": "extract history data", "usage": """[-f FORMAT] [--sort SORT]
[-s] [-t SAVE_TO] [-o] [-u] places_sqlite""",
     "args": [
         *REPEATEDARGS,
         (["-f", "--format"], {"default": DEFAULTHFORMATOPTIONS, "help": f"""
Which metadata fields to include and in which order. Default: {DEFAULTHFORMATOPTIONS}.
Options: {", ".join([f"{k} ({v})" for k, v in HFORMATOPTIONS.items()])}."""}),
         (["--sort"], {"choices":
                       [x for k in HFORMATOPTIONS for x in (k, k + 'r')],
                       "help": """Sort by a given metadata field.
Options are the same as for -f/--format, or followed by r for reverse order.
(Example: vr -> sort by visit epoch, reverse order.)"""}),
         ]},
    "b":                        # B (bookmarks)
    {"desc": "extract bookmarks data", "usage": """[-f FORMAT] [--sort SORT]
[-s] [-t SAVE_TO] [-o] [-u] places_sqlite""",
     "args": [
         *REPEATEDARGS,
         (["-f", "--format"], {"default": DEFAULTBFORMATOPTIONS, "help": f"""
Which metadata fields to include and in which order. Default: {DEFAULTBFORMATOPTIONS}.
Options: {", ".join([f"{k} ({v})" for k, v in BFORMATOPTIONS.items()])}."""}),
         (["--sort"], {"choices":
                       [x for k in BFORMATOPTIONS for x in (k, k + 'r')],
                       "help": """Sort by a given metadata field.
Options are the same as for -f/--format, or followed by r for reverse order.
(Example: vr -> sort by visit epoch, reverse order.)"""}),
     ]},
}


def msg(text):
    # type: (str) -> None
    """Utility for logs/errors, could be replaced with proper logging"""
    if not QUIET:
        print(f'{PROG}: {text}')


def readable_date_from_epoch(e):
    """Takes epoch in microseconds"""
    # type: (int) -> str
    return datetime.fromtimestamp(e/1000000).strftime(DATEFORMAT)


def epoch_from_readable_date(d):
    """Returns epoch in microseconds"""
    # type: (str) -> int
    return int(datetime.fromisoformat(d).timestamp()*1000000)


def get_visit_information(entry_dict, visit_dict, fmt):
    # type: (dict, dict, str) -> dict
    res = {}

    v = visit_dict.get('visit_date')

    # This architecture is from metaf but doesn't make as much sense
    # here since our calls are not heavy. It would probably cheaper to
    # preset all of them instead of having the lambdas. But maybe in
    # future we would want to add a field that would be heavier.
    dispatch = {
        'v': lambda: v,  # or 0 instead of None?
        'V': lambda: readable_date_from_epoch(v) if v else None,
        'i': lambda: entry_dict.get('id'),  # is this int or str?
        'u': lambda: entry_dict.get('url'),
        't': lambda: entry_dict.get('title'),
        'd': lambda: entry_dict.get('description'),
    }
    # ^ not sure if fallbacks should be None or 0 / ''. I want to be
    # able to tell if it didn't exist in the dictionary so I'm leaving
    # None for now but I'm not sure how csv handles it.

    for char in fmt:
        opt = HFORMATOPTIONS.get(char)
        if not opt or char not in dispatch:
            continue
        res[opt] = dispatch[char]()

    return res


def get_bookmark_path(cur, bookmark):
    # type: (sqlite3.Cursor, dict) -> str
    parents = []
    p_id = bookmark.get('parent', 0)
    while p_id > 1:
        cur.execute(f"SELECT * FROM moz_bookmarks WHERE id = {p_id}")
        parent = cur.fetchone()
        if not parent:
            msg(f'Parent {p_id} not found')
            return '?'
        parent = dict(parent)
        parents.append(parent.get('title', '?'))
        p_id = parent.get('parent', 0)
    return '/'.join(reversed(parents))


def get_keyword_alist(cur):
    # type: (sqlite3.Cursor) -> dict[int, str]
    alist = {}
    res = cur.execute("SELECT * FROM moz_keywords")
    for s in res:
        k = dict(s)
        alist[k.get('place_id')] = k.get('keyword')
    return alist


def update_keywords(cur, existing, keywords):
    # type: (sqlite3.Cursor, dict, dict) -> None
    changed = False
    url2keyword = None
    for b in existing:
        k = None
        if 'fk' in b:           # Update based on fk
            k = keywords.get(b.get('fk'))
        else:                   # Update based on URL
            if url2keyword is None:
                url2keyword = {}
                for id, keyword in keywords.items():
                    cur.execute(f"SELECT * FROM moz_places WHERE id = {id}")
                    place = cur.fetchone()
                    if not place:
                        msg(f"update_keywords: Place {id} not found")
                        continue
                    place = dict(place)
                    url2keyword[place.get('url')] = keyword
            k = url2keyword.get(b.get('url'))

        if k and k != b.get(BFORMATOPTIONS['k']):
            b[BFORMATOPTIONS['k']] = k
            changed = True
    if changed:
        msg('Keywords changed')


def get_bookmark_information(cur, bookmark_dict, place_dict, fmt, keywords={}):
    # type: (sqlite3.Cursor, dict, dict, str, dict) -> dict
    res = {}

    a = bookmark_dict.get('dateAdded')
    m = bookmark_dict.get('lastModified')

    dispatch = {
        'a': lambda: a,
        'A': lambda: readable_date_from_epoch(a) if a else None,
        'm': lambda: m,
        'M': lambda: readable_date_from_epoch(m) if m else None,
        'i': lambda: bookmark_dict.get('id'),
        'u': lambda: place_dict.get('url'),
        't': lambda: bookmark_dict.get('title'),
        'p': lambda: get_bookmark_path(cur, bookmark_dict),
        'k': lambda: keywords.get(bookmark_dict.get('fk')),
        'f': lambda: bookmark_dict.get('fk'),
    }

    for char in fmt:
        opt = BFORMATOPTIONS.get(char)
        if not opt or char not in dispatch:
            continue
        res[opt] = dispatch[char]()

    return res


def parse_csv(s):
    # type: str -> list
    res = []
    rows = list(csv.DictReader(s.splitlines()))
    keys = list(rows[0].keys())
    for row in rows:
        r = {}
        for field in keys:
            r[field] = int(row[field]) if field in INTFIELDS else row[field]
        res.append(r)
    return res


def read_existing(path):
    # type: str -> dict | None
    existing = None
    with open(path, "r") as f:
        existing = parse_csv(f.read())
    return existing


class CsvOutput():
    """Passed to csv module to get it write into a string instead of a file.
    Adapted from Bhavesh Poddar:
    https://levelup.gitconnected.com/building-csv-strings-in-python-32934aed5a9e
    """
    def __init__(self):
        self.lines = []

    def write(self, line):
        self.lines.append(line)

    def __str__(self):
        return ''.join(self.lines)


def export_csv(a):
    # type: (list) -> str
    fieldnames = [*list((a[0] if len(a) else {}).keys())]
    rows = [fieldnames]
    for item in a:
        rows.append([str(v) for v in item.values()])

    out = CsvOutput()
    writer = csv.writer(out)
    writer.writerows(rows)

    return str(out)


def hhasfields(d, fmt):
    # type: (dict, str) -> bool
    for c in fmt:
        if HFORMATOPTIONS.get(c) not in d:
            return False
    return True


def bhasfields(d, fmt):
    # type: (dict, str) -> bool
    for c in fmt:
        if BFORMATOPTIONS.get(c) not in d:
            return False
    return True


def hmerge(existing, new, fmt):
    # type: (list, list, str) -> list
    # Merge visits with existing but only the fields in fmt as there
    # may be fields in existing that are not in current fmt
    fields = [HFORMATOPTIONS[c] for c in fmt]
    return [{k: d[k] for k in fields} for d in existing] + new


def bmerge(existing, new, fmt):
    # type: (list, list, str) -> list
    """Create dictionary from existing and new with only the fields in fmt
    and no duplicate IDs
    """
    fields = [BFORMATOPTIONS[c] for c in fmt]
    by_id = {d['id']: {k: d[k] for k in fields} for d in existing}
    for d in new:
        by_id[d['id']] = d
    return list(by_id.values())


def cmd_h(args):
    save_to = args.save_to or DEFAULTSAVENAME
    fmt = args.format or DEFAULTHFORMATOPTIONS

    update_after = None
    existing = None

    # Fail fast if save file already exists and overwrite is False
    # unless update is True
    if args.save and not args.overwrite:
        if os.path.exists(save_to):
            if not args.update:
                msg(f'Save file \'{save_to}\' already exists. '
                    'Run with -u/--update if you wish to update it. '
                    'Run with -o/--overwrite if you wish to overwrite it. '
                    'Run with -t/--save-to to specify a different save file.')
                exit(1)

            existing = read_existing(save_to)
            if not len(existing):
                msg('Existing is empty. Either the file is empty or something '
                    'went wrong.' + S_UNDESIREDOVERWRITE)
                exit(1)
            one = existing[0]
            V = one.get(HFORMATOPTIONS['V'])
            v = one.get(HFORMATOPTIONS['v'])
            # Check we have dates
            if not v and not V:
                msg('Existing data has no visit dates. Without dates in the '
                    'data there is no reference point, so everything would '
                    'have to be queried from scratch.' + S_UNDESIREDOVERWRITE)
                exit(1)
            # Check format options are all there
            if not hhasfields(one, fmt):
                msg('Existing data does not contain all format '
                    'options, so everything would have to be queried from '
                    f'scratch. {one} | {fmt}'
                    + S_UNDESIREDOVERWRITE)
                exit(1)
            else:               # Proceed with the update
                # Sort data in order to get the most recent date in it
                if v:
                    existing.sort(key=lambda r: r[HFORMATOPTIONS['v']])
                else:
                    existing.sort(key=lambda r: r[HFORMATOPTIONS['V']])
                V = existing[-1].get(HFORMATOPTIONS['V'])
                v = existing[-1].get(HFORMATOPTIONS['v'])
                if not v:
                    v = epoch_from_readable_date(V)
                update_after = v
                msg(f'Adding visits after {v} ({readable_date_from_epoch(v)})')

    con = sqlite3.connect(f"file:{args.places_sqlite}?mode=ro", uri=True)
    con.text_factory = lambda data: str(data, errors="surrogateescape")
    con.row_factory = sqlite3.Row
    cur = con.cursor()

    query = "SELECT * FROM moz_places"
    query += f' WHERE last_visit_date > {update_after}' if update_after else ''
    res = cur.execute(query)
    entries = [dict(s) for s in res]

    # Get visits for each entry
    visits = []
    for entry in entries:
        query = ("SELECT * FROM moz_historyvisits "
                 f'WHERE place_id = {entry['id']}')
        query += f' AND visit_date > {update_after}' if update_after else ''
        cross = cur.execute(query)
        for s in cross:
            visits.append(get_visit_information(entry, dict(s), fmt))

    con.close()

    if not visits:
        msg("No new visits")

    visits = hmerge(existing, visits, fmt) if update_after else visits

    def sort_key(item):
        k = HFORMATOPTIONS[args.sort[0]]
        data_to_sort_by = item.get(k, None)
        if data_to_sort_by is None:
            msg(f"{k} not in entry data")
            data_to_sort_by = 0 if k in INTFIELDS else ''
        return data_to_sort_by

    if args.sort:
        reverse = True if len(args.sort) > 1 and args.sort[1] == 'r' else False
        msg(f'Sorting by {args.sort[0]}{" in reverse" if reverse else ""}')
        visits.sort(key=sort_key, reverse=reverse)

    dump = export_csv(visits)

    if args.save and not args.dryrun:
        open_as = 'w' if args.overwrite or args.update else 'x'
        with open(save_to, open_as) as f:
            f.write(dump)
            msg(f'Wrote to {save_to}')
    else:
        print(dump)


def cmd_b(args):
    save_to = args.save_to or DEFAULTSAVENAME
    fmt = args.format or DEFAULTBFORMATOPTIONS

    update_after = None
    existing = None

    # Fail fast if save file already exists and overwrite is False
    # unless update is True
    if args.save and not args.overwrite:
        if os.path.exists(save_to):
            if not args.update:
                msg(f'Save file \'{save_to}\' already exists. '
                    'Run with -u/--update if you wish to update it. '
                    'Run with -o/--overwrite if you wish to overwrite it. '
                    'Run with -t/--save-to to specify a different save file.')
                exit(1)

            existing = read_existing(save_to)
            if not len(existing):
                msg('Existing is empty. Either the file is empty or something '
                    'went wrong.' + S_UNDESIREDOVERWRITE)
                exit(1)
            one = existing[0]
            M = one.get(BFORMATOPTIONS['M'])
            m = one.get(BFORMATOPTIONS['m'])
            id = one.get(BFORMATOPTIONS['i'])
            # Check we have dates
            if not m and not M:
                msg('Existing data has no modification dates. Without dates '
                    'in the data there is no reference point, so everything '
                    'would have to be queried from scratch.'
                    + S_UNDESIREDOVERWRITE)
                exit(1)
            # Check we have IDs
            if not id:
                msg('Existing data has no IDs. Without IDs in the data'
                    'there is no way to know which bookmarks were modified.'
                    + S_UNDESIREDOVERWRITE)
                exit(1)
            # If keywords in format options, check we have URLs or fk
            if 'k' in fmt and not ('url' in one or 'fk' in one):
                msg('Updating keywords requires fk or URLs in the data.')
                exit(1)
            # Check format options are all there
            if not bhasfields(one, fmt):
                msg('Existing data does not contain all format '
                    'options, so everything would have to be queried from '
                    f'scratch. {one} | {fmt}'
                    + S_UNDESIREDOVERWRITE)
                exit(1)
            else:               # Proceed with the update
                # Sort data in order to get the most recent date in it
                if m:
                    existing.sort(key=lambda r: r[BFORMATOPTIONS['m']])
                else:
                    existing.sort(key=lambda r: r[BFORMATOPTIONS['M']])
                m = existing[-1].get(BFORMATOPTIONS['m'])
                if not m:
                    M = existing[-1].get(BFORMATOPTIONS['M'])
                    m = epoch_from_readable_date(M)
                update_after = m
                msg('Updating bookmarks after '
                    f'{m} ({readable_date_from_epoch(m)})')

    con = sqlite3.connect(f"file:{args.places_sqlite}?mode=ro", uri=True)
    con.text_factory = lambda data: str(data, errors="surrogateescape")
    con.row_factory = sqlite3.Row
    cur = con.cursor()

    keywords = {}
    if 'k' in fmt:
        keywords = get_keyword_alist(cur)
        update_keywords(cur, existing or {}, keywords)

    query = "SELECT * FROM moz_bookmarks"
    query += f' WHERE lastModified > {update_after}' if update_after else ''
    res = cur.execute(query)
    entries = [dict(s) for s in res]

    # Get place for each bookmark
    bookmarks = []
    for entry in entries:
        if not entry['fk']:
            continue
        query = ("SELECT * FROM moz_places "
                 f'WHERE id = {entry['fk']}')
        cross = cur.execute(query)
        for s in cross:
            bookmarks.append(
                get_bookmark_information(cur, entry, dict(s), fmt, keywords))

    con.close()

    if not bookmarks:
        msg("No new bookmarks")

    bookmarks = bmerge(existing, bookmarks, fmt) if update_after else bookmarks

    def sort_key(item):
        k = BFORMATOPTIONS[args.sort[0]]
        data_to_sort_by = item.get(k, None)
        if data_to_sort_by is None:
            msg(f"{k} not in entry data")
            data_to_sort_by = 0 if k in INTFIELDS else ''
        return data_to_sort_by

    if args.sort:
        reverse = True if len(args.sort) > 1 and args.sort[1] == 'r' else False
        msg(f'Sorting by {args.sort[0]}{" in reverse" if reverse else ""}')
        bookmarks.sort(key=sort_key, reverse=reverse)

    dump = export_csv(bookmarks)

    if args.save and not args.dryrun:
        open_as = 'w' if args.overwrite or args.update else 'x'
        with open(save_to, open_as) as f:
            f.write(dump)
            msg(f'Wrote to {save_to}')
    else:
        print(dump)


def parse_args():
    parser = argparse.ArgumentParser(prog=PROG)
    parser.suggest_on_error = True
    subparsers = parser.add_subparsers(dest="command", required=True)
    descs = []
    for k, v in COMMANDS.items():
        if v.get('desc'):       # description generation
            descs.append(f"{v['desc']} ({k})")
        if k == "":             # arguments on top parser
            for args, kwargs in v['args']:
                parser.add_argument(*args, **kwargs)
            continue
        subparser = subparsers.add_parser(
            k, help=f"[-h|--help] {v.get('usage')}")
        for args, kwargs in v['args']:
            subparser.add_argument(*args, **kwargs)
        # Set handler
        subparser.set_defaults(func=v.get('func'))
    # Add generated description
    if len(descs):
        descs[-1] = f"or {descs[-1]}"
    parser.description = f"A utility script to \
{' '.join(descs)} from a places.sqlite file."
    # Parse args / print help and quit if no args
    # (Primer https://stackoverflow.com/a/47440202/18396947)
    return parser.parse_args(sys.argv[1:] or ['--help'])


COMMANDS['h']['func'] = cmd_h
COMMANDS['b']['func'] = cmd_b


def main():
    # type: () -> None
    global QUIET

    args = parse_args()
    QUIET = args.quiet

    args.func(args)


if __name__ == '__main__':
    main()
