#!/usr/bin/env bash
# NOMSFICHIER="/run/user/1000/gvfs/smb-share:server=apollo,share=p/tmp.txt"
# while read n; do
#     res=$(find . -maxdepth 1 -name "${n//[$'\t\r\n']}")
#     # if [ -z "$res" ]; then echo "$n"; fi
#     [ ! -z "$res" ] && echo "$res"
# done < "$NOMSFICHIER"

#CHEMINSFICHIER="/run/user/1000/gvfs/smb-share:server=apollo,share=p/abs.txt"

encode_utf8_octal() {
  printf '%s' "$1" | od -An -tu1 | \
  LC_ALL=C awk '
  {
    for (i=1; i<=NF; i++) {
      if ($i < 128)
        printf "%c", $i
      else
        printf "\\%03o", $i
    }
  }
  END { print "" }'
}

CHEMINSFICHIER="/tmp/20260103abs"
somme=0
while read chemin; do
    nom="${chemin##*/}"
    # nom="$(encode_utf8_octal "$nom")"
    # nom="${nom/\\303\\240/a\\314\\200}"
    # nom="${nom/\\303\\250/e\\314\\200}"
    #echo "$nom"
    nom="$(printf "$nom")"
    #echo "$nom"
    if [ -e "$nom" ]; then
        #true
        poids=$(du -ks "./$nom" | cut -f 1)
        # echo "$poids"
        somme=$((somme + poids))
    else
        echo "@@ N'EXISTE PAS"
        echo "$nom"
        #somme=$((somme + 1))
        # nom2=$(ls | grep ".*${nom:0:20}.*")
        # echo "$nom :: $nom2"
    fi
done < "$CHEMINSFICHIER"
echo "$somme"
