#!/usr/bin/env sh
# Queued mpv
# 2026-03-15 21:44
# Based on the work of ZaxonXP (gapless_play.sh) and gabreek (mpv-handler-queue)
#
# Dependencies:
# - mpv > 0.38.0
# - yt-dlp
# - socat
#
# Usage:
# queuedmpv [--rawoutput] [--reverse] [--purgecache] [--purgepos] [--pos=N] (QUERY|INPUTFILE)
# QUERY = any link or search accepted by yt-dlp.
# * queuedmpv scsearch1000:fjellstrom
# * queuedmpv youtube.com/@slowgermanlistening/videos
# * queuedmpv youtube.com/?v=zADVzO7m5qM
# INPUTFILE = a file where each line contains a link to a video or a yt-id.
# * queuedmpv Example_list.txt
# * queuedmpv <(yt-dlp --no-warnings --print "%(webpage_url)s" ytsearch2:cat)

NAME="${0##*/}"
soc="/tmp/queuedmpv-soc"
mpvargs="--quiet --prefetch-playlist=yes --force-window=yes"
pos=
file=
loaded=
should_save=1
mpvoutput_colour="magenta"
mpvoutput_filter='^\[vo\/gpu-next\/libplacebo|^MESA-INTEL:|^\[osd\/libass'
max_read_attempts=5
CACHE_DIR="$HOME/.cache/$NAME"
mkdir -p "$CACHE_DIR"

help() {
    cat <<EOF
Usage: $NAME [options] (QUERY|INPUTFILE)

QUERY = any link or search accepted by yt-dlp.
INPUTFILE = a file where each line contains a link to a video or a yt-id.

Options:

-h | --help   Show this help text and exit.
--rawoutput   Don't filter and colour mpv output.
--reverse     Read video list in reverse order. Does not support pseudofiles.
--purgecache  Remove file that caches the video list for a given QUERY.
--purgepos    Remove file that stores current position in the video list.
--pos=N       Force starting position N.

Examples:
* $NAME scsearch1000:fjellstrom
* $NAME youtube.com/@slowgermanlistening/videos
* $NAME youtube.com/?v=zADVzO7m5qM
* $NAME Example_list.txt
* $NAME <(yt-dlp --no-warnings --print "%(webpage_url)s" ytsearch2:cat)
EOF
}

get_link() {    # if $1 contains a yt-id return its link, $1 otherwise
    id=$(echo "$1" | sed -n \
's/.*\(^\|[ |]\)\([A-Za-z0-9_-]\{11\}\)\([ |]\|$\).*/\2/p')
    [ -z "$id" ] && echo "$1" || echo "https://www.youtube.com/watch?v=$id"
}

get_link_at_line_number() {     # $1 = 0-based line number
    [ ! -e "$file" ] && file=${file%.tmp}
    n=$(($1 + 1))
    line=$(sed -n ${n}p "$file")
    attempt=0
    while [ -z "$line" ]; do
        [ "$attempt" -gt "$max_read_attempts" ] && break
        sleep 1
        line=$(sed -n ${n}p "$file")
        attempt=$((attempt + 1))
    done
    get_link "$line"
}

store_pos() {                   # $1 = pos, $2 = pos file
    if [ -n "$1" ] && [ -n "$2" ]; then
        echo "$1" > "$2"
        echo "$NAME: Stored position $1 in $2"
    fi
}

ipc() { # $1 = command, rest = passed as the remaining arguments to printf
    cmd="$1\n"
    shift
    printf "$cmd" "$@" | socat - "$soc"
}

json_escape() {
    if [ $# -gt 0 ]; then
        printf '%s' "$1" |
            sed -e 's/\\/\\\\/g' \
                -e 's/"/\\"/g'
    else                        # stdin
        sed -e 's/\\/\\\\/g' \
            -e 's/"/\\"/g'
    fi
}

preload_link() { # $1 = link. optional: $2 = index, $3 = loadfile flags
    info=$(yt-dlp --no-warnings --get-title --get-url "$1")
    title=$(echo "$info" | head -1 | json_escape)
    video=$(echo "$info" | sed -n 2p)
    audio=$(echo "$info" | sed -n 3p)
    i=-1
    [ -n "$2" ] && i=$2
    if [ -z "$video" ]; then
        "$NAME: Preload failed, empty video. yt-dlp output: $info"
        return 1
    fi
    flags="insert-at"
    [ -n "$3" ] && flags=$3
    ipc '{"command": ["loadfile", "%s", "%s", %s, {"force-media-title": "%s", "audio-file": "%s"}]}'\
        "$video" "$flags" "$i" "$title" "$audio"
}

get_data() {                    # $1 = ipc output
    echo "$1" | sed -n 's/.*"data":\(.*\)}/\1/p'
}

maybe_load_pos() {              # $1 = pos, $2 (optional) = index
    if [ "$1" -gt -1 ] && ! echo "$loaded" | grep -q "\[$1:"; then
        echo "$NAME: Preloading pos $1"
        i=-1
        [ -n "$2" ] && [ "$2" -gt -1 ] && i=$2
        link=$(get_link_at_line_number $1)
        if [ -n "$link" ]; then
            preload_link "$link" "$i"
            loaded="$loaded[$1:$(date +%s)]"
            # if index is before current, loadfile will bump playlist-pos
            [ $i -gt -1 ] && [ ! $i -gt $playlist_pos ] && playlist_pos_bump_only=yes
        else
            echo "$NAME: No link at pos $1"
        fi
    fi
}

playlist_pos=
prev_playlist_pos=

handle_playlist_pos_changed() { # $1 = line
    playlist_pos=$(get_data "$line")
    if [ -n "$playlist_pos_bump_only" ]; then
        playlist_pos_bump_only=
        prev_playlist_pos=$playlist_pos
        return
    fi
    if [ "$playlist_pos" -gt -1 ]; then
        if [ -n "$prev_playlist_pos" ]; then
            offset=$((playlist_pos - prev_playlist_pos))
            pos=$((pos + offset))
            [ -n "$should_save" ] && store_pos "$pos" "$pos_file"
        fi
        echo "$NAME: playlist-pos changed to $playlist_pos (pos $pos) [$(date '+%F %T')]"
        maybe_load_pos $((pos + 1))
        maybe_load_pos $((pos - 1)) $((playlist_pos))
        prev_playlist_pos=$playlist_pos
    fi
}

observe() {
    fifo=$(mktemp -u)
    mkfifo "$fifo"
    socat "$soc" - < "$fifo" |
        while read -r line; do
            case "$line" in
                *'"name":"playlist-pos","data"'*)
                    handle_playlist_pos_changed "$line";;
                *'"name":"duration","data"'*)
                    echo "$NAME: $(get_data "$line") seconds duration";;
                *'"name":"media-title","data"'*)
                    echo "$NAME: $(get_data "$line") media-title";;
            esac
    done &
    exec 3>"$fifo"
    printf '{"command": ["observe_property", 1, "playlist-pos"]}\n' >&3
    printf '{"command": ["observe_property", 1, "duration"]}\n' >&3
    printf '{"command": ["observe_property", 1, "media-title"]}\n' >&3
}

handle_output() {               # $1 = output file
  perl -sne "
use Term::ANSIColor;
\$|=1;
if (/$mpvoutput_filter/) { }
else { print colored(\$_, '$mpvoutput_colour') }
" < "$1"
}

get_cache_file() {  # $1 = query
    pad=..............          # padding for human-readable component
    h=$(echo -n "$1" | sed 's/[^a-zA-Z0-9]*//g' | rev | cut -c -14 | rev)
    #     [14 chars human readable].[15 chars md5sum].txt
    echo "$CACHE_DIR/$h${pad:${#h}}.$(echo -n "$1" | md5sum | cut -c -15).txt"
}

get_pos_file() {  # $1 = query
    cache_file=$(get_cache_file "$1")
    echo "${cache_file%.txt}.pos.txt"
}

rawoutput_flag=
reverse_flag=
purgecache_flag=
purgepos_flag=

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            help
            exit;;
        --rawoutput)
            rawoutput_flag=1;;
        --reverse)
            reverse_flag=1;;
        --nosave)
            should_save=;;
        --purgecache)
            purgecache_flag=1;;
        --purgepos)
            purgepos_flag=1;;
        --pos=*)
            pos="${1#--pos=}"
            echo "$NAME: Forcing position $pos";;
        --)
            shift
            break;;
        -*)
            echo "$NAME: Unknown option $1" >&2
            exit 1;;
        *)
            break;;
    esac
    shift
done

# by peterh https://stackoverflow.com/a/21188136/18396947
get_abs_filename() {
  filename=$1
  parentdir=$(dirname "${filename}")
  if [ -d "${filename}" ]; then
      echo "$(cd "${filename}" && pwd)"
  elif [ -d "${parentdir}" ]; then
    echo "$(cd "${parentdir}" && pwd)/$(basename "${filename}")"
  fi
}

query=$1
[ -z "$query" ] && { help; exit 1; }
[ -f "$query" ] && query=$(get_abs_filename "$query") # normalise file path

cache_file=$(get_cache_file "$query")
pos_file=$(get_pos_file "$query")
reverse_cache_file="${cache_file%.txt}-reverse.txt"
reverse_pos_file="${pos_file%.txt}-reverse.txt"

reverse_pos() {
    len=
    if [ -e "$reverse_cache_file" ]; then
        len=$(wc -l < "$reverse_cache_file")
    elif [ -e "$cache_file" ]; then
        len=$(wc -l < "$cache_file")
    fi
    if [ -e "$pos_file" ] && [ ! -e "$reverse_pos_file" ] && [ -n "$len" ]; then
        pos="$(cat "$pos_file")"
        reverse_pos=$(($len - $pos - 1))
        echo $reverse_pos > "$reverse_pos_file"
        echo "$NAME: Calculated reverse pos $reverse_pos > $reverse_pos_file"
    fi
}

is_newer() {                   # $1 and $2 = paths to files or folders
    find "$1" -prune -newer "$2" | grep -q . && return 0 || return 1
}

if [ "$reverse_flag" = 1 ]; then # calculate reverse cache and pos if possible
    if [ -f "$query" ]; then    # INPUTFILE and non-pseudofile
        if [ ! -e "$reverse_cache_file" ] ||
               is_newer "$query" "$reverse_cache_file"; then
            tac "$query" > "$reverse_cache_file"
            echo "$NAME: Wrote reversed list to cache $reverse_cache_file"
        fi
    else                        # QUERY
        if [ -r "$cache_file" ] && [ ! -e "$reverse_cache_file" ]; then
            tac "$cache_file" > "$reverse_cache_file"
            echo "$NAME: Wrote reversed cached list to $reverse_cache_file"
        fi
    fi
    [ -z "$pos" ] && reverse_pos
    cache_file=$reverse_cache_file
    pos_file=$reverse_pos_file
fi

if [ "$purgecache_flag" = 1 ] && [ -f "$cache_file" ]; then
    rm "$cache_file"
    echo "$NAME: Purged cache file $cache_file"
fi
if [ "$purgepos_flag" = 1 ] && [ -f "$pos_file" ]; then
    rm "$pos_file"
    echo "$NAME: Purged pos file $pos_file"
fi

ytdlp_pid=
cache_pid=

cleanup() {                     # kill forked processes
    [ -n "$ytdlp_pid" ] && kill "$ytdlp_pid" 2>/dev/null
    [ -n "$cache_pid" ] && kill "$cache_pid" 2>/dev/null
    exit 130
}

trap cleanup INT TERM

try_restore_pos() {
    if [ -r "$pos_file" ] && [ "$(cat "$pos_file")" -gt 0 ]; then
        pos="$(cat "$pos_file")"
        echo "$NAME: Restoring position $pos"
    fi
}

finalise_cache_fork() {
    (    # finalise cache when yt-dlp is done irrespective of read
        tail --pid="$ytdlp_pid" -f /dev/null
        if [ -s "$cache_file.tmp" ]; then
            mv "$cache_file.tmp" "$cache_file"
            echo "$NAME: Finalised cache $cache_file"
        fi
    ) &
    cache_pid=$!
}

if [ -r "$query" ]; then        # INPUTFILE
    file=$query
    if [ -f "$query" ]; then    # real file (not pseudofile)
        [ "$reverse_flag" = 1 ] && [ -r "$cache_file" ] && file=$cache_file
        [ -z "$pos" ] && try_restore_pos
    else
        echo "$NAME: Cache and position cannot be saved for pseudofiles"
        should_save=
    fi
else                            # QUERY
    if [ -r "$cache_file" ]; then # cache
        echo "$NAME: Using cached list $cache_file"
        file=$cache_file
        [ -z "$pos" ] && try_restore_pos
    else                        # no cache
        ytdlp_args="--no-warnings"
        if [ -n "$pos" ] || ([ -r "$pos_file" ] && [ "$(cat "$pos_file")" -gt 0 ]); then
            [ -z "$pos" ] && pos="$(cat "$pos_file")"
            if [ "$reverse_flag" = 1 ]; then
                ytdlp_args="$ytdlp_args -I -$(($pos + 1))::-1"
            else
                ytdlp_args="$ytdlp_args --playlist-start $(($pos + 1))"
            fi
            cache_file="${cache_file%.txt}-start${pos}.txt"
            echo "$NAME: Restoring position $pos"
        else                    # no pos
            [ "$reverse_flag" = 1 ] && ytdlp_args="$ytdlp_args -I ::-1"
        fi
        if [ -n "$should_save" ]; then
            file="$cache_file.tmp"
        else
            file=$(mktemp -u)
            mkfifo "$file"
        fi
        stdbuf -oL yt-dlp $ytdlp_args --print "%(webpage_url)s" "$query" \
               > "$file" &  # line-buffered cache
        ytdlp_pid=$!
        [ -n "$should_save" ] && finalise_cache_fork
    fi
fi

[ -z "$pos" ] && pos=0

# Run mpv
mpvargs="$mpvargs --idle=once --input-ipc-server="
if [ "$rawoutput_flag" = 1 ]; then
    mpv $mpvargs"$soc" &
else
    mpv_output=$(mktemp -u)
    mkfifo "$mpv_output"
    mpv $mpvargs"$soc" > "$mpv_output" 2>&1 &
    handle_output "$mpv_output" &
fi

sleep 1
observe
preload_link "$(get_link_at_line_number "$pos")" 0 replace
wait
