#!/usr/bin/env bash
# Non-persistent reminders via scheduled notifications and sound
# 2025-11-26 13:45
#
# Dependencies:
# - notify-send
# - paplay
#
# Usage:
# rappel 24h hello
# rappel 5h 10m "drink water"

SON="/usr/share/sounds/freedesktop/stereo/complete.oga"

NOM="${0##*/}"

helptext() {
    echo "Usage: $NOM [délai] \"[message]\"
Exemple: $NOM 5h 10m \"Boire de l'eau\"
Le dernier argument est le message, tous les autres sont passés à sleep.
Délai unités s/m/h/d. Avec plusieurs arguments séparés par un espace, \
il prend la somme de ces valeurs."
}

if [ $# -lt 2 ]; then
    helptext
    exit 1
fi

message="${@:$#}"

(
    sleep ${@:1:$# - 1}
    if [ ! $? = 0 ]; then
        echo "$NOM: un problème est survenu lors de l'exécution du sleep"
        exit 1
    fi
    notify-send -u critical "Rappel" "$message"
    paplay "$SON"
) & disown
