#!/usr/bin/env bash
# Lock and log inputs
# 2026-01-05 08:13
#
# Purpose: Prevent inputs while I sleep, and log when they happen
#
# Dependencies:
# - xtrlock
# - (Optional) Emacs daemon (to run a command on unlock)
#
# Usage:
# sommeil
# Usually activated with a hotkey
# To unlock type (blindly) user password. If it fails don't panic, try again
# (previous inputs could interfere. ESC to clear) or try unplugging and
# replugging the keyboard.

FICHIER=~/sommeil.log
LOCKAPP=xtrlock
DATEFMT='+%H:%M'
TIMETOSLEEPAFTERINPUTBEFOREDIMMINGSCREEN=5s
# avoid logging the timestamp if another input occurred before n seconds
LOGTHRESHOLD=50
EMACSCMD='(with-current-buffer (file-name-nondirectory p-main-file) (insert-file-contents "~/sommeil.log"))'
T_ABANDON="Aucun processus %s, abandon"

NOM="${0##*/}"

now=0
echo -n "" > "$FICHIER"
jobpid=
cleanup() {
    if [ ! -z $jobpid ]; then
        kill $jobpid
        jobpid=
    fi
}

quit() {
    cleanup
    command -v emacsclient >/dev/null 2>&1 && emacsclient --eval "$EMACSCMD"
    exit
}

maybeabandon() {
    pgrep "$LOCKAPP" >/dev/null 2>&1
    if [[ ! "$?" = 0 ]]; then
        printf "$NOM: ${T_ABANDON}\n" "$LOCKAPP"
        quit
    fi
}

maybeeteindre() {
    sleep $TIMETOSLEEPAFTERINPUTBEFOREDIMMINGSCREEN
    xset dpms force off
}

xtrlock &
xinput test-xi2 --root |
    while read -r line; do
        # echo "$line"  # DEBUG
        case "$line" in
            *\(KeyRelease\))
                if [[ $now < $(($EPOCHSECONDS - $LOGTHRESHOLD)) ]]; then
                    echo -n "$(date "$DATEFMT") " >> "$FICHIER"
                    now=$EPOCHSECONDS
                fi
                cleanup
                maybeeteindre &
                jobpid=$!
                ;;
            # Pressing a mouse key to quit. Commented out due to my
            # tendency to press it by accident.
            # *\(ButtonRelease\))
            #     pkill "$LOCKAPP"
            #     echo "$NOM: mouse interrupt"
            #     quit
            #     ;;
            EVENT*)
                maybeabandon
                ;;
        esac
    done
