#!/usr/bin/env bash
# Control background music (mpv processes)
# 2026-01-05 19:37
#
# Dependencies:
# - mpv
# - rofi
# - audio files below (sons)
#
# Usage:
# soncontrol rofi
# brings up rofi interface to start/stop the different audio files

NOM="${0##*/}"

declare -A sons=(
    ["tokyo"]="/media/Windows/Users/pm/Music/Tokyo's Most Dangerous Metropolitan Expressway in Heavy Rain [zFio5Tbqy8Y].opus"
    ["obscur"]="/media/Windows/Users/pm/Music/clair obscur [LAQZfeETFbg].m4a"
)
declare -A volumes=(
    ["tokyo"]=100
    ["obscur"]=80
)
DEFAULT=tokyo
mpvargs=(--no-video --loop --save-position-on-quit --load-scripts=no)

options="start\nstop"
for son in "${!sons[@]}"; do
    options="$options\nstart$son\nstop$son"
done

get_name() {
    son="${1#$2}"
    [ -z "$son" ] && son="$DEFAULT"
    echo "$son"
}

kill_pid() {
    name="$1"
    pid=$(cat "/tmp/${name}pid" 2>/dev/null)
    [ ! -z $pid ] && kill $pid
}

save_pid() {
    pid="$1"
    name="$2"
    echo "$pid" > "/tmp/${name}pid"
}

case "$1" in
    rofi)
        res=$(echo -en "$options" | rofi -i -cycle -dmenu -p "soncontrol")
        $0 $res
        ;;
    start*)
        son="$(get_name "$1" start)"
        kill_pid "$son"
        mpv "${sons[$son]}" --volume=${volumes[$son]} ${mpvargs[@]} &
        save_pid "$!" "$son"
        ;;
    stop*)
        son="$(get_name "$1" stop)"
        kill_pid "$son"
        save_pid  # intentionally no argument in order to empty it
        ;;
esac
