#!/usr/bin/env python3
# Toggle plover
# 2026-01-06 22:39
"""Script to run Plover from source without tox,
and send commands to a running instance.

Instructions:
1. Modify `PLOVER_PATH` to be the path to your local Plover repository
2. Modify `PLUGINS` to be a list of paths to repositories of plugisn you wish
   to load
3. Run this script to launch or toggle Plover, passing any arguments you wish
   to pass to Plover or Plover run command. e.g. `toggleplover focus`
4. To install plugins just add their paths to `PLUGINS`, don't use
   `plover --script plover_plugins install` as it uses pip to install them and
   this will not work without tox or venv.

Script dependencies:
psutil

Plover dependencies:
1. Minimal:
appdirs, hid, pkginfo, plover-stroke, Pygments, pyserial, packaging,
setuptools, wcwidth
2. GUI:
PySide6-Essentials
3. Plugins:
readme-renderer[md], requests-cache, requests-futures, rtf_tokenize
4. Linux-only:
python-xlib, evdev, psutil
5. Windows-only:
plyer
6. MacOS-only:
appnope, pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-Quartz

Created: 2026-01-06 22:39 as a bash script
         2026-01-24 03:00 became a python script
"""
import os
import sys
import psutil

PLOVER_PATH = '/media/Windows/Users/pm/dev/reps/plover'
PLUGINS = [
    '/media/Windows/Users/pm/dev/reps/pyhuntsman/plover-huntsman-plugin',
]

ARGS_TO_MAIN_PLOVER = ['--version', '-s', '--script', '-g', '--gui']

for path in PLUGINS:
    sys.path.insert(0, path)
sys.path.insert(0, PLOVER_PATH)


def is_running(script):
    # kabapy https://stackoverflow.com/a/50063190/18396947
    for q in psutil.process_iter():
        if q.name().startswith('python'):
            if (len(q.cmdline()) > 1
                    and script in q.cmdline()[1]
                    and q.pid != os.getpid()):
                return True
    return False


if (not is_running("plover")
        or len(sys.argv) > 1 and sys.argv[1] in ARGS_TO_MAIN_PLOVER):
    from plover.scripts.main import main  # noqa: E402
    sys.exit(main())
else:
    from plover.scripts.send_command import main  # noqa: E402
    if len(sys.argv) < 2:
        sys.argv.append('toggle')
    sys.exit(main())

# NOTES:
# Other methods to toggle plover:

# 1. Click on the tray icon
# eval $(xdotool getmouselocation --shell)
# xdotool mousemove 990 5 click --delay 500 1
# xdotool mousemove $X $Y

# 2. Ask Plover (slow)
# plover -s plover_send_command toggle
