#!/usr/bin/env bash
# Verify validity of xml files with exclusions
# 2025-12-05 04:01 / 04:10
#
# Dependencies:
# - xmllint
#
# Usage:
# Run in folder containing the files to verify

FILESGLOB=*.doentry
T_IGNORED="Ignoré :"
T_CURRENT="Traitement :"

ignore=("1A71DD04CF8141EBBC6DB74819B9A127 botched (Zhu Q's conflicted copy 2020-12-16).doentry" # corrupted
        "56399F901C154422A5287F7D0C16205D.doentry"  # 2019
        "9FD95EB57DD3419D8388A1F8C1B02560.doentry"  # 2017
       )

COUNTER=1
for xmlfile in $FILESGLOB; do
    for ign in "${ignore[@]}"; do
        if [[ "$xmlfile" == "$ign" ]]; then
            echo "$COUNTER $T_IGNORED $xmlfile"
            let COUNTER++
            continue 2
        fi
    done
    echo "$COUNTER $T_CURRENT $xmlfile";
    xmllint --format "$xmlfile" > /dev/null;
    if [ $? != 0 ]; then
        break;
    fi;
    let COUNTER++
done
