#!/usr/bin/env bash
# Command to launch my win98 qemu virtual machine
# 2026-01-30 08:02
#
# Based on https://computernewb.com/wiki/QEMU/Guests/Windows_98
# and https://www.qemu.org/docs/master/system/images.html
#
# Dependencies (for this script):
# - qemu
# - paths in the variables VM_IMG, VM_SHARE, VM_CD defined below
#
# Requirements to set up VM:
# - https://github.com/oerg866/win98-quickinstall for win98 itself
# - https://github.com/JHRobotics/softgpu for graphics
# - AC97 driver linked in softgpu readme ^ for sound
#
# Usage:
# vmman
#
# Notes:
# Careful with the shared folder, vvfat is pretty fragile, you should not
# change anything it from the host while vm is running. It's also limited
# to 500 MB max, there is allegedly a way to get it to 2 GB but I've not
# worked it out. ISOs can be used to transfer larger files, with the advantage
# that you can change them while the vm is running. Personally to transfer
# from guest to host I use the vvfat share, and from host to guest I use ISOs.

VM_IMG=/home/pm/pm/vm/win98.img
VM_SHARE=/home/pm/pm/vm/share
VM_CD=/home/pm/Downloads/win98qi_v0.9.6_stock.iso
# Change iso in the cdrom while running with:
# change ide1-cd0 path/to/iso

qemu_cmd_win98=(
    qemu-system-i386
    -display gtk,zoom-to-fit=on,show-menubar=off
    -device lsi53c895a,id=vm.scsi_controller
    -drive if=none,id=vm.hda_drive,file=$VM_IMG
    -device scsi-hd,id=vm.hda,drive=vm.hda_drive,bus=vm.scsi_controller.0,bootindex=1
    -drive if=none,id=vvfat,file=fat:rw:$VM_SHARE,format=raw
    -device scsi-hd,drive=vvfat,bootindex=2
    -cdrom $VM_CD
    -device VGA,vgamem_mb=64
    -cpu host
    -m 256
    -M pc,hpet=off,acpi=on,usb=on,accel=kvm
    -netdev user,id=lan
    -device rtl8139,netdev=lan
    -device usb-tablet
    -rtc base=localtime
    -monitor stdio
    # sound
    -device AC97
)

VM_IMG=/home/pm/pm/vm/win10.img
VM_CD=/home/pm/Downloads/en-us_windows_10_iot_enterprise_ltsc_2021_x64_dvd_257ad90f.iso

qemu_cmd_win10=(
    qemu-system-x86_64
    -enable-kvm
    -m 8G
    -smp 4
    -cpu host
    -drive file=$VM_IMG,format=qcow2
    -nic user,id=nic0,smb=/home/pm/Downloads/builds/retype-1.7.0-prerelease3-windows/
    # -cdrom $VM_CD
    # -boot d
)

VM_IMG=/home/pm/pm/vm/macos.img
VM_CD="/home/pm/Downloads/macOS_Catalina_10.15.7(1).iso"
# macOSCatalina.iso
OPENCORE=/home/pm/pm/vm/macOS-Simple-KVM/ESP.qcow2
#/home/pm/Downloads/OpenCore.qcow2

qemu_cmd_macos=(
    qemu-system-x86_64
    -enable-kvm
    -m 8G
    -smp 4
    -cpu host
    -drive file=$VM_IMG,format=qcow2
    -cdrom $VM_CD
    -boot d
    # qemu-system-x86_64
    # -enable-kvm
    # -machine q35,accel=kvm
    # -m 8G
    # -smp 4
    # -cpu Penryn,kvm=on,vendor=GenuineIntel
    # -bios /usr/share/edk2/x64/OVMF.4m.fd
    # -device ich9-ahci,id=sata
    # -drive file=$OPENCORE,if=none,format=qcow2,id=opencore
    # -device ide-hd,drive=opencore,bus=sata.0
    # -drive file=$VM_CD,if=none,format=raw,id=installation
    # -device ide-hd,drive=installation,bus=sata.1
    # -drive file=$VM_IMG,if=none,format=qcow2,id=disk
    # -device ide-hd,drive=disk
    # -vga virtio
)

# "${qemu_cmd_macos[@]}"

# "${qemu_cmd[@]}"

# https://github.com/LongQT-sea/OpenCore-ISO
# https://github.com/notAperson535/OneClick-macOS-Simple-KVM

args=(
    -enable-kvm
    -m 8G
    -machine q35,accel=kvm
    -cpu Haswell-noTSX,model=158
    -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" \
    -smbios type=2 \
    -device intel-hda -device hda-output \
    -drive if=pflash,format=raw,readonly=on,file="/home/pm/Downloads/OVMF_CODE.fd" \
    -drive if=pflash,format=raw,file="/home/pm/Downloads/OVMF_VARS.fd" \
    -vga qxl
    -usb -device usb-ehci,id=ehci -device usb-kbd,bus=ehci.0 -device usb-tablet,bus=ehci.0 \
    -netdev user,id=net0
    -device vmxnet3,netdev=net0,id=net0,mac=52:54:00:c9:18:27
    -monitor telnet:127.0.0.1:5801,server,nowait
    -device ich9-ahci,id=sata
    -drive id=OpenCore,if=none,format=raw,file="/home/pm/Downloads/LongQT-OpenCore-v0.7.iso"
    -device ide-hd,bus=sata.2,drive=OpenCore
    # -cdrom "/home/pm/Downloads/macOS_Catalina_10.15.7(1).iso"
    -drive id=SystemDisk,if=none,file="/home/pm/pm/vm/macos.img" \
    -device ide-hd,bus=sata.4,drive=SystemDisk \
)

#qemu-system-x86_64 "${args[@]}"

# Adjust these paths
VM_IMG=~/pm/vm/macos.img
VM_ISO=~/Downloads/macOS_Catalina_10.15.7.iso
OC_ISO=~/Downloads/LongQT-OpenCore-v0.7.iso
OVMF_CODE=~/Downloads/OVMF_CODE.fd
OVMF_VARS=~/Downloads/OVMF_VARS.fd

args=(
    -enable-kvm
    -m 8G
    -machine q35,accel=kvm
    -cpu Haswell-noTSX,model=158
    -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
    -smbios type=2
    -device intel-hda -device hda-output
    -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE"
    -drive if=pflash,format=raw,file="$OVMF_VARS"
    -vga qxl
    -usb -device usb-ehci,id=ehci -device usb-kbd,bus=ehci.0 -device usb-tablet,bus=ehci.0
    -netdev user,id=net0
    -device vmxnet3,netdev=net0,id=net0,mac=52:54:00:c9:18:27
    -monitor telnet:127.0.0.1:5801,server,nowait
    -device ich9-ahci,id=sata
    -drive if=none,id=OpenCore,media=cdrom,file="$OC_ISO"
    -device ide-cd,bus=sata.0,drive=OpenCore,bootindex=1
    -drive if=none,id=Installer,media=cdrom,file="$VM_ISO"
    -device ide-cd,bus=sata.1,drive=Installer
    -drive if=none,id=SystemDisk,file="$VM_IMG"
    -device ide-hd,bus=sata.2,drive=SystemDisk
)

qemu-system-x86_64 "${args[@]}"
