#!/usr/bin/env bash
# Command to launch my win98 qemu virtual machine
# 2026-01-30 08:02
#
# Based on https://computernewb.com/wiki/QEMU/Guests/Windows_98
# and https://www.qemu.org/docs/master/system/images.html
#
# Dependencies (for this script):
# - qemu
# - paths in the variables VM_IMG, VM_SHARE, VM_CD defined below
#
# Requirements to set up VM:
# - https://github.com/oerg866/win98-quickinstall for win98 itself
# - https://github.com/JHRobotics/softgpu for graphics
# - AC97 driver linked in softgpu readme ^ for sound
#
# Usage:
# vmman
#
# Notes:
# Careful with the shared folder, vvfat is pretty fragile, you should not
# change anything it from the host while vm is running. It's also limited
# to 500 MB max, there is allegedly a way to get it to 2 GB but I've not
# worked it out. ISOs can be used to transfer larger files, with the advantage
# that you can change them while the vm is running. Personally to transfer
# from guest to host I use the vvfat share, and from host to guest I use ISOs.

VM_IMG=/home/pm/pm/vm/win98.img
VM_SHARE=/home/pm/pm/vm/share
VM_CD=/home/pm/Downloads/win98qi_v0.9.6_stock.iso
# Change iso in the cdrom while running with:
# change ide1-cd0 path/to/iso

qemu_cmd=(
    qemu-system-i386
    -display gtk,zoom-to-fit=on,show-menubar=off
    -device lsi53c895a,id=vm.scsi_controller
    -drive if=none,id=vm.hda_drive,file=$VM_IMG
    -device scsi-hd,id=vm.hda,drive=vm.hda_drive,bus=vm.scsi_controller.0,bootindex=1
    -drive if=none,id=vvfat,file=fat:rw:$VM_SHARE,format=raw
    -device scsi-hd,drive=vvfat,bootindex=2
    -cdrom $VM_CD
    -device VGA,vgamem_mb=64
    -cpu host
    -m 256
    -M pc,hpet=off,acpi=on,usb=on,accel=kvm
    -netdev user,id=lan
    -device rtl8139,netdev=lan
    -device usb-tablet
    -rtc base=localtime
    -monitor stdio
    # sound
    -device AC97
)

"${qemu_cmd[@]}"
