volume=140
speed=1.5
screenshot-directory=~/pm/r/mpv/
screenshot-template="%ty%tm%td%tH%tM-%F-%wH%wM%wS"
ytdl-raw-options=yes-playlist=
ytdl-format=30016+30232/best[height<=384]/bestaudio
input-ipc-server=/tmp/mpvsocket
prefetch-playlist=yes
cache=yes
demuxer-readahead-secs=300
demuxer-max-bytes=500M
